### ISSUE TITLE
Implement Logging with Configurable Log File and Verbosity Levels

### ISSUE THREAD

**Issue by jiaccarino** [matthewl121/ACME_Corp_CLI_Interface#15]
### Description: 
- store in environment variable $LOG_FILE
- use verbosity level in environment variable $LOG_LEVEL

There are many views on what and how much to log. Some good resources are (1) [this blog](https://testing.googleblog.com/2013/06/optimal-logging.html); and (2) [this SO post](https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels).

![Image](https://github.com/user-attachments/assets/38a7d898-d08f-4526-998b-3a38c9782be3)

Acceptance Criteria:

    The log file path is correctly configured using the $LOG_FILE environment variable.
    The verbosity level is set according to the $LOG_LEVEL environment variable, filtering log messages based on the specified level.
    Log entries include appropriate details based on the verbosity level set.
    Logging functionality is tested to ensure correct file output and verbosity control.

**Comment by glenscheng** [comment]
possible solution:

```
const fs = require('fs');

let verbosity = 1; // Default verbosity level

function logToFile(message, level = 1) {
  if (level <= verbosity) {
    fs.appendFileSync('output.log', message + '\n');
    if (verbosity > 1) console.log(message); // Also log to console if verbosity > 1
  }
}

// Set verbosity level (0: silent, 1: file only, 2+: file and console)
function setVerbosity(level) {
  verbosity = level;
}

// Usage examples:
setVerbosity(2);
logToFile('High priority message', 1);
logToFile('Less important info', 2);
logToFile('Debug info', 3);
```

**Comment by glenscheng** [comment]
https://github.com/matthewl121/ACME_Corp_CLI_Interface/tree/glen_log_file

src/utils/log.ts

use logToFile() with message level instead of console.log()

EXAMPLES:
```
logToFile('Informational messages', 1);
logToFile('Debug messages', 2);

logToFile("Final Metrics:", 1); 
logToFile(metrics, 1); // pass object directly
logToFile("Weighted Metrics:", 1);
logToFile(weightedMetrics, 1); // pass object directly
logToFile(`Final Score: ${finalScore}`, 1);
```
