### ISSUE TITLE
Implement Concurrency for Metric Calculation

### ISSUE THREAD

**Issue by jiaccarino** [matthewl121/ACME_Corp_CLI_Interface#17]
### Description:

Implement concurrency to improve the performance of metric calculations. This will be done in two stages:
1. Threading for URL Parsing:
> Create separate threads for each function responsible for parsing URLs associated with each metric.
> After parsing is complete, join the threads to synchronize before moving on to the next step.

2. Threading for Score Calculation:
> Create separate threads for the functions responsible for calculating the scores for each metric.
> After the score calculations are completed, join the threads to ensure all threads finish before proceeding.

This approach should parallelize the work, improving the efficiency of both URL parsing and score computation.

Acceptance Criteria:
- Threads are created and used for URL parsing for each metric, ensuring concurrency for the parsing process.
- Threads are created and used for score calculation for each metric, ensuring concurrency in the scoring process.
- All threads are joined at the appropriate stages (after URL parsing and after score calculation).
- The implementation ensures thread safety and proper synchronization between threads.
- The code runs efficiently and improves the overall performance by leveraging concurrency.

**Comment by glenscheng** [comment]
Finished prototyping in my fork repo, prototype_concurrency branch. 

Will be able to add in concurrency once the code for metric calculations are finished.
