### ISSUE TITLE
Set Permissions for the run File to Executable

### ISSUE THREAD

**Issue by jiaccarino** [matthewl121/ACME_Corp_CLI_Interface#21]
### Description:

- Ensure the run file has its permissions set to executable.
- Use chmod +x run to make the script executable on a Linux machine.
- Confirm that the file can be executed directly by invoking ./run.

**Acceptance Criteria:**

- The run file is executable and can be invoked directly using ./run.
- The file has the correct permissions set using chmod +x run.

**Comment by jiaccarino** [comment]
The file “run” should have the following CLI when executed on a Linux machine (note that you can use whatever CLI you want; you can then wrap that CLI within this auto-grader-friendly CLI):

“./run install”
./run URL_FILE"
"./run test"

**Comment by matthewl121** [comment]
./run install and ./run url_file complete, chmod +x run is ran
