### ISSUE TITLE
Create test suite and testing framework

### ISSUE THREAD

**Issue by jiaccarino** [matthewl121/ACME_Corp_CLI_Interface#22]
- create 20+ test cases
- achieve 80%+ structural coverage
- output to stdout: “X/Y test cases passed. Z% line coverage achieved.”

**Example:**
Total: 10
Passed: 9
Coverage: 90%
9/10 test cases passed. 90% line coverage achieved.

**Comment by glenscheng** [comment]
How do I calculate structural coverage? import testing framework to do the heavy-lifting maybe..

**Comment by glenscheng** [comment]
JEST is ass... it keeps logging stuff to the console and me and ChatGPT don't know how to stop it from doing so, going to have to try another framework, or see if there is a way I can do manual calculations for line structure coverage

**Comment by glenscheng** [comment]
Testing framework is added (JEST), just need to create 19 more tests

**Comment by glenscheng** [comment]
20 tests will comprise of 4 URLS, all 5 metrics each. glen_test_suite2 branch has template tests of the 5 metrics.
