### ISSUE TITLE
GitHub Actions Workflow for ESLint Linting - YAML

### ISSUE THREAD

**Issue by jiaccarino** [matthewl121/ACME_Corp_CLI_Interface#32]
Description:

We should implement a GitHub Actions workflow that automatically runs ESLint on our codebase to ensure code quality and adherence to linting rules. 

Workflow Details:

Name: ESLint
    Trigger Events:
        On push to the main branch.
        On pull request to the main branch.
        Scheduled linting run every Friday at 00:30 UTC.

Jobs:

    Job Name: eslint
    Runs on: ubuntu-latest
    Permissions:
        contents: read
        security-events: write (required for SARIF uploads)
        actions: read (for private repositories only)

Steps:

    Checkout the code using actions/checkout@v4.
    Install ESLint (version 8.57.0) and the @microsoft/eslint-formatter-sarif (version 2.1.7).
    Create a results directory to store linting results.
    Run ESLint on the entire codebase using the configuration file eslint.config.mjs. The output will be saved in the SARIF format for later analysis.
    Upload the ESLint results as a SARIF file using github/codeql-action/upload-sarif@v3 for reporting and further analysis.

Benefits:

    Automates linting as part of the CI pipeline, reducing manual checks.
    Ensures consistent code quality across all push and pull requests.
    Scheduled linting ensures long-term code health.
    Integration with GitHub security tools (SARIF) for advanced analysis and reporting.

Next Steps:

    Add the workflow file to the repository under .github/workflows/eslint.yml.
    Ensure the necessary dependencies are installed in the project.

**Comment by matthewl121** [comment]
Request has been completed, main branch for repo now contains workflow eslint.yml under .github/workflows that succeeds upon runtime
