### ISSUE TITLE
Implement ./run URL_FILE Command

### ISSUE THREAD

**Issue by jiaccarino** [matthewl121/ACME_Corp_CLI_Interface#34]
### Description:

- Create a command ./run URL_FILE that takes as input the absolute path of a file containing a list of URLs (newline-delimited, ASCII-encoded).
- The URLs may be from either the npmjs.com domain or GitHub.
- The script should analyze these URLs and produce output in NDJSON format, with each row containing:

> - URL
> - NetScore
> - NetScore_Latency
> - RampUp
> - RampUp_Latency
> - Correctness
> - Correctness_Latency
> - BusFactor
> - BusFactor_Latency
> - ResponsiveMaintainer
> - ResponsiveMaintainer_Latency
> - License
> - License_Latency

- Scores must be in the range [0,1], where 0 indicates failure and 1 indicates success. Latency values should be reported in seconds, rounded to three decimal places.
- The NetScore should be calculated as a weighted sum of other scores. Choose and justify the weights based on Sarah’s priorities in your report.
- The script should exit with 0 on success, and a non-zero value if there is a failure.

**Acceptance Criteria:**

- A file containing URLs can be processed and outputs NDJSON with the required fields.
- The NetScore calculation is a weighted sum of the sub-scores.
- The latency values are accurate and rounded to three decimal places.
- The script exits with 0 on success, non-zero otherwise.

**Comment by matthewl121** [comment]
./run url_file complete, executable now compiles an absolute path to url.txt and logs all output into logfile
